name: Deploy Evidence.dev

on:
  push:
    branches: [ main ]  # or 'main' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Evidence sources
        env:
          EVIDENCE_SOURCE__warehouse__host: localhost
          EVIDENCE_SOURCE__warehouse__port: 5437
          EVIDENCE_SOURCE__warehouse__database: warehouse
          EVIDENCE_SOURCE__warehouse__user: ${{ secrets.POSTGRES_USERNAME }}
          EVIDENCE_SOURCE__warehouse__password: ${{ secrets.POSTGRES_PASSWORD }}
        run: npm run sources

      - name: Build Evidence project
        env:
          EVIDENCE_SOURCE__warehouse__host: localhost
          EVIDENCE_SOURCE__warehouse__port: 5437
          EVIDENCE_SOURCE__warehouse__database: warehouse
          EVIDENCE_SOURCE__warehouse__user: ${{ secrets.POSTGRES_USERNAME }}
          EVIDENCE_SOURCE__warehouse__password: ${{ secrets.POSTGRES_PASSWORD }}
        run: npm run build:strict
          
      - name: Backup current build
        run: |
          if [ -d "./build-live" ]; then
            mv ./build-live ./build-backup
          fi
          
      - name: Deploy new build
        run: |
          # Move new build to live directory
          mv ./build ./build-live
          
          # Ensure nginx container is running and can access files
          docker-compose up -d
          
      - name: Cleanup
        run: |
          # Clean up failed builds older than 1 day
          find . -name "build-failed*" -type d -mtime +1 -exec rm -rf {} + || true