name: Deploy Evidence.dev

on:
  push:
    branches: [ main ]  # or 'main' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Evidence project
        env:
          ## Add any database connection environment variables
          EVIDENCE_SOURCE__warehouse__host: localhost
          EVIDENCE_SOURCE__warehouse__port: 5437
          EVIDENCE_SOURCE__warehouse__database: warehouse
          EVIDENCE_SOURCE__warehouse__user: ${{ secrets.POSTGRES_USERNAME }}
          EVIDENCE_SOURCE__warehouse__password: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          
          # Build the project (this will connect to your local PostgreSQL)
          npm run sources
          npm run build
          
      - name: Backup current build
        run: |
          if [ -d "./build-live" ]; then
            mv ./build-live ./build-backup
          fi
          
      - name: Deploy new build
        run: |
          # Move new build to live directory
          mv ./build ./build-live
          
          # Ensure nginx container is running and can access files
          docker-compose up -d
          
          # Wait a moment for container to be ready
          sleep 5
          
          # Test that the site is responding
          if curl -f http://localhost:80 > /dev/null 2>&1; then
            echo "✅ Deployment successful!"
            # Clean up backup
            rm -rf ./build-backup
          else
            echo "❌ Deployment failed, rolling back..."
            mv ./build-live ./build-failed
            if [ -d "./build-backup" ]; then
              mv ./build-backup ./build-live
            fi
            echo "Rollback completed"
            exit 1
          fi
          
      - name: Cleanup
        run: |
          # Clean up failed builds older than 1 day
          find . -name "build-failed*" -type d -mtime +1 -exec rm -rf {} + || true